@startsalt
@startuml
(*) --> "
{{
salt
{+
<b>ログイン
  ID         | "12345 "
  パスワード | "****  "
  [  OK   ]
}
}}
" as choose
choose -right-> "
{{
salt
{+
<b>メインメニュー(管理者)
[勤怠]
[1日の予定]
[メール]
[会議使用状況]
[ユーザー管理]
[メールログ確認]
}
}}
" as adimnChoose
choose -down-> "
{{
salt
{+
<b>メインメニュー
[勤怠]
[1日の予定]
[メール]
[会議使用状況]
}
}}
"
@enduml
@endsalt