@startsalt
@startuml
(*) --> "
{{
salt
{+
<b>メインメニュー(管理者)
[勤怠]
[1日の予定]
[メール]
[会議使用状況]
[ユーザー管理]
[メールログ確認]
}
}}
" as subMenu
subMenu -right-> "
{{
salt
{+
<b>ユーザー管理
[新規登録]
[編集]
[削除]
{#
ユーザーID | ユーザー名 | 権限名
value1 | value2 | value3
value1 | value2 | value3
value1 | value2 | value3
}
}
}}
" as subMenu2
subMenu -down-> "
{{
salt
{+
<b>製作中
}
}}
"
@enduml
@endsalt