@startuml
left to right direction
skinparam packageStyle rectangle
actor 一般ユーザー
actor 管理者
rectangle ポータルシステム {
  一般ユーザー -- (勤怠入力・参照)
  一般ユーザー -- (1日の予定入力・参照)
  一般ユーザー -- (簡易メール送受信)
  一般ユーザー -- (会議室利用予約・参照)
  一般ユーザー -- (全体周知)
  一般ユーザー -- (個人メモ)
  一般ユーザー -- (プロジェクト管理)
  (勤怠入力・参照) -- 管理者
  (1日の予定入力・参照) -- 管理者
  (簡易メール送受信) -- 管理者
  (会議室利用予約・参照) -- 管理者
  (ユーザー情報更新・参照) -- 管理者
  (勤怠一括エクセル出力) -- 管理者
  (全体周知) -- 管理者
  (個人メモ) -- 管理者
  (プロジェクト管理) -- 管理者
}
@enduml