@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "ユーザーマスタ" as user {
  *ユーザーID : varchar(20) <<PK>>
  --
  *名前 : text
  *パスワード : text
  *権限ID : numeric <<FK>>
  *ログインフラグ : numeric
  *削除フラグ : numeric
  *更新時刻 : timestamp
}

entity "権限マスタ" as auth {
  *権限ID : numeric <<PK>> 
  --
  *権限名 : text
  *更新時刻 : timestamp
}

entity "勤怠テーブル" as attend {
  *ユーザーID : varchar(20) <<FK>>
  *勤務開始時間 : timestamp
  *勤務終了時間 : timestamp 
  *休憩時間 : numeric
  *更新日時 : timestamp
}

entity "メールテーブル" as mail {
  *送信者ユーザーID : varchar(20) <<FK>>
  *受信者ユーザーID : varchar(20) <<FK>>
  *件名 : text
  *メッセージ : text
  *追加日時 : timestamp
}

entity "予定テーブル" as plan {
  *ユーザーID : varchar(20) <<FK>>
  *予定内容 : varchar(10)
  *開始日時 : timestamp
  *終了日時 : timestamp 
  *備考 : text
  *追加日時 : timestamp
}

entity "ミーティングルームテーブル" as meeting {
  *ルームID : varchar(20) <<PK>>
  *ルーム名 : text 
  *開放開始時間 : text
  *開放終了時間 : text
  *更新日時 : timestamp
}

entity "使用状況テーブル" as use {
  *ユーザーID : varchar(20) <<FK>>
  *ルームID : varchar(20) <<FK>>
  *開始日時 : timestamp
  *終了日時 : timestamp 
  *追加日時 : timestamp
}

user }|--|| auth
user ||--o{ attend
user ||--o{ mail
user ||--o{ plan
user ||--o{ use
use }o--|| meeting

@enduml