@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor "ユーザー" as user
participant "勤怠フォーム" as kintai_form
participant "勤怠ロジック" as kintai_logic
participant "勤怠DBアクセス" as kintai_data_acces
database "データベース" as db

user -> kintai_form: 先月ボタン押下
kintai_form -> kintai_form: 先月ボタンクリックイベント
activate kintai_form
kintai_form -> kintai_form: 先月を引数に設定
kintai_form -> kintai_form:勤怠情報設定 起動と同一なので省略
activate kintai_form
kintai_form -> kintai_logic:
kintai_logic -> kintai_data_acces:
kintai_data_acces -> db:
db --> kintai_data_acces:
kintai_data_acces --> kintai_logic:
kintai_logic --> kintai_form:
kintai_form --> kintai_form:
deactivate kintai_form
kintai_form --> user:
deactivate kintai_form

user -> kintai_form: 来月ボタン押下
kintai_form -> kintai_form: 来月ボタンクリックイベント
activate kintai_form
kintai_form -> kintai_form: 来月を引数に設定
kintai_form -> kintai_form:勤怠情報設定 起動と同一なので省略
activate kintai_form
kintai_form -> kintai_logic:
kintai_logic -> kintai_data_acces:
kintai_data_acces -> db:
db --> kintai_data_acces:
kintai_data_acces --> kintai_logic:
kintai_logic --> kintai_form:
kintai_form --> kintai_form:
deactivate kintai_form
kintai_form --> user:
deactivate kintai_form

@enduml