@startsalt
@startuml
(*) --> "
{{
salt
{+
<b>メインメニュー(一般)
ログインユーザー：田中
[勤怠]
[タスク]
[メール]
[会議使用状況]
[ログアウト]
}
}}
" as subMenu
subMenu -right-> "
{{
salt
{+
<b>勤怠
ログインユーザー：田中
11月
[先月] | [来月] 
{#
日付 | 曜日 | 勤務開始 | 勤務終了 | 休憩 | 残業
1 | 火 | 9:00 | 18:00 | 1:00 | 0
2 | 水 | 9:00 | 19:30 | 1:00 | 1:30
3 | 木 | 9:00 | 18:00 | 1:00 | 0
}
[保存] | [終了]
}
}}
" as mail
subMenu -down-> "
{{
salt
{+
<b>メール
ログインユーザー：田中
[受信ボックス] | [送信ボックス] | [新規作成] | [返信]
{#
日時 | 名前 | 件名 | メッセージ内容
2019/10/30 8:34  | 轟 | はじめましての挨拶
2019/11/14 16:01  | 斎藤 | お知らせ
2019/11/23 10:12  | 石神 | 休みの連絡
}
[終了]
}
}}
" as mail_transfer
mail_transfer -down-> "
{{
salt
{+
<b>新規作成
[宛先] | useridIshigami(石神)
件名 | "お知らせ"
メッセージ
{S
お知らせ
.
.
.
.
}
[送信]
}
}}
" as atesaki
atesaki -down-> "
{{
salt
{+
<b>宛先
{#
名前
轟(IdTodorogi)
斎藤(IdSaito)
石神(IdIshi)
}
[OK]
}
}}
" as subMenu3
subMenu -left-> "
{{
salt
{+
<b>製作中
}
}}
" as subMenu4
subMenu -up-> "
{{
salt
{+
<b>製作中
}
}}
"
@enduml
@endsalt