@startsalt
@startuml
(*) --> "
{{
salt
{+
<b>メインメニュー(一般)
ログインユーザー：田中
[勤怠]
[予定]
[メール]
[ログアウト]
}
}}
" as menu
menu -right-> "
{{
salt
{+
<b>勤怠
ログインユーザー：田中
11月
{[先月] | [来月] }
{#
日付 | 曜日 | 勤務開始 | 勤務終了 | 休憩 | 残業
1 | 火 | 9:00 | 18:00 | 1:00 | 0
2 | 水 | 9:00 | 19:30 | 1:00 | 1:30
3 | 木 | 9:00 | 18:00 | 1:00 | 0
}
{[保存] | [終了]}
}
}}
" as kintai
menu -down-> "
{{
salt
{+
<b>メール
ログインユーザー：田中
{[受信ボックス] | [送信ボックス] | [新規作成] | [返信]}
{#
日時 | 名前 | 件名 | メッセージ内容
2019/10/30 8:34  | 轟 | はじめましての挨拶
2019/11/14 16:01  | 斎藤 | お知らせ
2019/11/23 10:12  | 石神 | 休みの連絡
}
[終了]
}
}}
" as mail
mail -down-> "
{{
salt
{+
<b>新規作成
[宛先] | useridIshigami(石神)
件名 | "お知らせ"
メッセージ
{S
お知らせ
.
.
.
.
}
[送信]
}
}}
" as createMail
createMail -down-> "
{{
salt
{+
<b>宛先
{#
名前
轟(IdTodorogi)
斎藤(IdSaito)
石神(IdIshi)
}
[OK]
}
}}
" as atesaki
menu -left-> "
{{
salt
{+
<b>予定
ログインユーザー：田中
{[先週] | [来週] }
{#
名前 | 11/5(月) | 11/6(火) | 11/7(水) | 11/8(木) | 11/9(金) | 11/10(土) | 11/11(日)
轟 | 会議(10:00〜11:00) | "" | 会議(10:00〜11:00) | "" | "" | "" | "" 
斎藤 | "" | 休み | "" | "" | "" | "" | 移行作業(終日) 
石神 | "" | "" | "" | 外出(13:00〜終日)) | "" | "" | ""
}
{[予定追加] | [予定編集] | [終了]}
}
}}
" as schedool
schedool -down-> "
{{
salt
{+
<b>予定追加
{予定内容： | ^選択してください^}
{新規追加： | "　　　　　　　　"}
{施設： | ^使用する場合は選択してください^}
{ ^2019^ | 年 | ^12^ | 月 | ^1^ | 日 | (火) | ^9^ | 時 | ^30^ | 分 
 〜 | ^2019^ | 年 | ^12^ | 月 | ^1^ | 日 | (火) | ^10^ | 時 | ^30^ | 分}
[追加]
施設利用状況
{#
施設 | 11/5(月) | 11/6(火) | 11/7(水) | 11/8(木) | 11/9(金) | 11/10(土) | 11/11(日)
会議室1 | 10:00〜11:00 | "" | 10:00〜11:00 | "" | "" | "" | "" 
会議室2 | "" | 14:00〜16:00 | "" | "" | "" | "" | 20:00〜21:00 
軽運動室 | "" | "" | "" | 8:00〜9:00 | "" | "" | ""
}
}
}}
" as schedoolAdd
schedool -up-> "
{{
salt
{+
<b>予定編集
{予定内容： | ^選択してください^}
{新規追加： | "　　　　　　　　"}
{施設： | ^使用する場合は選択してください^}
{ ^2019^ | 年 | ^12^ | 月 | ^1^ | 日 | (火) | ^9^ | 時 | ^30^ | 分 
 〜 | ^2019^ | 年 | ^12^ | 月 | ^1^ | 日 | (火) | ^10^ | 時 | ^30^ | 分}
{[保存] | [削除]}
施設利用状況
{#
施設 | 11/5(月) | 11/6(火) | 11/7(水) | 11/8(木) | 11/9(金) | 11/10(土) | 11/11(日)
会議室1 | 10:00〜11:00 | "" | 10:00〜11:00 | "" | "" | "" | "" 
会議室2 | "" | 14:00〜16:00 | "" | "" | "" | "" | 20:00〜21:00 
軽運動室 | "" | "" | "" | 8:00〜9:00 | "" | "" | ""
}
}
}}
"
@enduml
@endsalt