@startsalt
@startuml
(*) --> "
{{
salt
{+
<b>メインメニュー(一般)
ログインユーザー：田中
[勤怠]
[タスク]
[メール]
[会議使用状況]
[ログアウト]
}
}}
" as subMenu
subMenu -right-> "
{{
salt
{+
<b>勤怠
ログインユーザー：田中
11月
[先月] | [来月] 
{#
日付 | 曜日 | 勤務開始 | 勤務終了 | 休憩 | 残業
1 | 火 | 9:00 | 18:00 | 1:00 | 0
2 | 水 | 9:00 | 19:30 | 1:00 | 1:30
3 | 木 | 9:00 | 18:00 | 1:00 | 0
}
[保存] | [終了]
}
}}
" as subMenu2
subMenu -down-> "
{{
salt
{+
<b>製作中
}
}}
" as subMenu3
subMenu -left-> "
{{
salt
{+
<b>製作中
}
}}
" as subMenu4
subMenu -up-> "
{{
salt
{+
<b>製作中
}
}}
"
@enduml
@endsalt