@startsalt
@startuml
(*) --> "
{{
salt
{+
<b>ログイン
  ID         | "12345 "
  パスワード | "****  "
  [  ログイン   ]
}
}}
" as choose
choose -right-> "
{{
salt
{+
<b>メインメニュー(管理者)
[勤怠]
[タスク]
[メール]
[会議使用状況]
[ユーザー管理]
[勤怠の一括エクセル出力]
[ログアウト]
}
}}
" as adimnChoose
choose -down-> "
{{
salt
{+
<b>メインメニュー(一般)
ログインユーザー：田中
[勤怠]
[タスク]
[メール]
[会議使用状況]
[ログアウト]
}
}}
"
@enduml
@endsalt