@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor "ユーザー" as user
participant "予定フォーム" as plan_form
participant "予定更新フォーム" as plan_update_form
participant "予定ロジック" as plan_logic
participant "予定DBアクセス" as plan_data_acces
database "データベース" as db

user -> plan_form: 表のセルクリック
plan_form -> plan_form: 表のセルクリックイベント
activate plan_form
plan_form -> plan_form: 引数にユーザー情報を設定
plan_form -> plan_update_form: 予定更新フォームのインスタンス生成
plan_update_form -> plan_update_form: コンストラクタ
activate plan_update_form
plan_update_form -> plan_update_form:ユーザー情報をプロパティに設定
alt クリックされたセルの値が空の時
    plan_update_form -> plan_update_form: 追加画面表示
    activate plan_update_form
    plan_update_form -> plan_logic: 予定ロジックのインスタンス生成
    plan_update_form -> plan_logic: 予定内容取得
    activate plan_logic
    plan_logic -> plan_data_acces: 予定内容取得
    activate plan_data_acces
    plan_data_acces -> db: 予定内容取得SQL
    db --> plan_data_acces: 予定内容データ
    plan_data_acces --> plan_logic:予定内容リスト
    deactivate plan_data_acces
    plan_logic --> plan_update_form: 予定内容リスト
    deactivate plan_logic
    plan_update_form -> plan_logic: 施設情報取得
    activate plan_logic
    plan_logic -> plan_data_acces: 施設情報取得
    activate plan_data_acces
    plan_data_acces -> db: 施設情報取得SQL
    db --> plan_data_acces: 施設情報データ
    plan_data_acces --> plan_logic:施設情報リスト
    deactivate plan_data_acces
    plan_logic --> plan_update_form: 施設情報リスト
    deactivate plan_logic
    plan_update_form -> plan_update_form: 引数に今日の日付を設定
    plan_update_form -> plan_update_form: 施設利用状況表示
    activate plan_update_form
    plan_update_form -> plan_logic: 一週間の施設表示情報取得
    activate plan_logic
    plan_logic -> plan_data_acces: 施設利用情報取得
    activate plan_data_acces
    plan_data_acces -> db: 施設利用情報取得SQL
    db --> plan_data_acces: 施設利用情報データ
    plan_data_acces --> plan_logic:施設利用情報リスト
    deactivate plan_data_acces
    plan_logic -> plan_data_acces: 施設一覧情報取得
    activate plan_data_acces
    plan_data_acces -> db: 施設一覧情報取得SQL
    db --> plan_data_acces: 施設一覧情報データ
    plan_data_acces --> plan_logic:施設一覧情報リスト
    deactivate plan_data_acces
    plan_logic -> plan_logic: 施設表示情報リストのインスタンスを生成
    loop 施設一覧情報リストの数だけループ
        plan_logic -> plan_logic: 施設表示情報リストに施設表示情報インスタンスを追加
        plan_logic -> plan_logic: 施設一覧情報の施設名を施設表示情報の施設名に設定
        plan_logic -> plan_logic: 施設一覧情報の施設IDで施設利用情報リストを検索
        plan_logic -> plan_logic: 検索結果を施設表示情報の施設利用情報リストに設定
    end
    plan_logic --> plan_update_form: 施設表示情報リスト
    deactivate plan_logic
    loop 施設表示情報リストの数だけループ
        plan_update_form -> plan_update_form: 施設表示情報の施設名を表のセルに表示
        loop 施設情報リストの数だけループ
            plan_update_form -> plan_update_form: 開始日時と終了日時から該当のセルに時間を表示
        end
    end
    plan_update_form --> plan_update_form:戻り値無し
    deactivate plan_update_form
    plan_update_form -> plan_update_form:予定内容リストに「選択してください」を追加
    plan_update_form -> plan_update_form:予定内容リストを画面のコンボボックスに設定
    plan_update_form -> plan_update_form:施設情報リストに「使用する場合は選択してください」を追加
    plan_update_form -> plan_update_form:施設情報リストを画面のコンボボックスに設定
    plan_update_form -> plan_update_form:画面の初期日時は今日の日付と業務の定時を設定
    plan_update_form --> user: 予定追加画面
    plan_update_form --> plan_update_form: 戻り値無し
    deactivate plan_update_form
else 引数の画面モードが編集の時
    plan_update_form -> plan_update_form:編集画面表示
end


@enduml