@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor "ユーザー" as user
participant "メールフォーム" as mail_form
participant "新規作成フォーム" as mail_create_form
participant "メールロジック" as mail_logic
participant "メールDBアクセス" as mail_data_acces
database "データベース" as db

user -> mail_create_form: 送信ボタン押下
mail_create_form -> mail_create_form: 送信ボタンクリックイベント
activate mail_create_form
mail_create_form -> mail_create_form: 送信確認のダイアログボックス
mail_create_form --> user: 送信確認
user -> mail_create_form: はいorいいえ
opt 送信確認がいいえの時
    mail_create_form --> user: 処理を終了    
end
loop プロパティのメール情報リストの数だけループ
    mail_create_form -> mail_create_form: 画面の件名をメール情報の件名に設定
    mail_create_form -> mail_create_form: 画面のメッセージをメール情報のメッセージに設定
    mail_create_form -> mail_logic: メール送信
    activate mail_logic
    mail_logic -> mail_data_acces: メール送信保存
    activate mail_data_acces
    mail_data_acces -> db: メール送信保存SQL
    db --> mail_data_acces:
    mail_data_acces --> mail_logic:
    deactivate mail_data_acces
    mail_logic --> mail_create_form:
    deactivate mail_logic
end
mail_create_form -> mail_create_form: 送信完了メッセージを出力
mail_create_form -> mail_create_form: 新規作成画面を閉じる
mail_create_form --> user: 
deactivate mail_create_form

@enduml