@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor "ユーザー" as user
participant "新規作成フォーム" as mail_create_form
participant "宛先フォーム" as adress_form
participant "メールロジック" as mail_logic
participant "共通ロジック" as common_logic
participant "共通DBアクセス" as common_data_acces
participant "メールDBアクセス" as mail_data_acces
database "データベース" as db

user -> mail_create_form: 宛先ボタン押下
mail_create_form -> mail_create_form: 宛先ボタンクリックイベント
activate mail_create_form
mail_create_form -> mail_create_form: メール情報リストのインスタンス生成
mail_create_form -> adress_form: インスタンス生成
mail_create_form -> adress_form: 引数にメール情報リスト
adress_form -> adress_form: コンストラクタ
activate adress_form
adress_form -> mail_logic: アドレス情報取得
activate mail_logic
mail_logic -> common_logic: アドレス情報取得
activate common_logic
common_logic -> common_data_acces: アドレス情報取得
activate common_data_acces
common_data_acces -> db: アドレス情報取得SQL
db --> common_data_acces: アドレス情報データ
common_data_acces --> common_logic: アドレス情報リスト
deactivate common_data_acces
common_logic --> mail_logic: アドレス情報リスト
deactivate common_logic
mail_logic -> mail_logic: アドレス情報リストをメール情報リストに設定
mail_logic --> adress_form: メール情報リスト
deactivate mail_logic
adress_form -> adress_form: プロパティのメール情報リストに設定
loop メール情報リストの数だけループ
    adress_form -> mail_logic: アドレス名生成
    activate mail_logic
    mail_logic -> mail_logic: ユーザーIDとユーザー名から宛先名を作成
    mail_logic --> adress_form: アドレス名
    deactivate mail_logic
    adress_form -> adress_form: コントロールの名前にユーザーIDを設定
    adress_form -> adress_form: 宛先名をコントロールに表示
end
adress_form --> mail_create_form: 
deactivate adress_form
mail_create_form -> adress_form: 宛先フォーム起動
adress_form --> user: 宛先画面 

user -> adress_form: OKボタン押下
activate adress_form
adress_form -> adress_form: メール情報リストのインスタンス生成
opt 選択されているアドレスがある時
    loop 選択されているアドレスの数だけループ
        adress_form -> adress_form: 選択アドレスのコントロールの名前を取得
        adress_form -> adress_form: コントロールの名前でメール情報リストをユーザーIDで検索
        adress_form -> adress_form: 検索されたメール情報をメール情報リストに追加
    end
end
adress_form -> adress_form: 上記のメール情報リストをプロパティのメール情報リストに設定
adress_form -> adress_form: 宛先画面を閉じる
adress_form --> mail_create_form: 
deactivate adress_form
mail_create_form -> mail_create_form: プロパティのメール情報リストを参照
opt メール情報リストがnullではない時
    loop メール情報リストの数だけループ
        mail_create_form -> mail_logic: アドレス名生成
        activate mail_logic
        mail_logic -> mail_logic: ユーザーIDとユーザー名から宛先名を作成
        mail_logic --> mail_create_form: アドレス名
        deactivate mail_logic
        mail_create_form -> mail_create_form: アドレス名をカンマ区切りの文字列で連結
    end
    mail_create_form -> mail_create_form: 連結したアドレス名を画面に表示
    mail_create_form -> mail_create_form: 送信ボタンを活性にする
end
mail_create_form --> user: 
deactivate mail_create_form

@enduml