@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor "ユーザー" as user
participant "新規作成フォーム" as mail_create_form
participant "宛先" as adress_form
participant "メールロジック" as mail_logic
participant "メールDBアクセス" as mail_data_acces
database "データベース" as db

user -> mail_create_form: 宛先ボタン押下
mail_create_form -> mail_create_form: 宛先ボタンクリックイベント
activate mail_create_form
mail_create_form -> adress_form: インスタンス生成
mail_create_form -> adress_form: 引数に
adress_form -> adress_form: コンストラクタ
activate adress_form
adress_form -> mail_logic: アドレス情報取得
activate mail_logic
mail_logic -> mail_data_acces: アドレス情報リスト取得
activate mail_data_acces
mail_data_acces -> db: アドレス情報取得SQL
db --> mail_data_acces: アドレス情報データ
mail_data_acces --> mail_logic: アドレス情報リスト
deactivate mail_data_acces
mail_logic -> mail_logic: ユーザー名とユーザーIDを合わせたハッシュキーを作成
mail_logic -> mail_logic: アドレス情報リストにキーを設定して、ハッシュマップを生成
mail_logic --> adress_form: アドレスハッシュマップ
deactivate mail_logic
adress_form -> adress_form: プロパティのアドレスハッシュマップに設定
adress_form -> adress_form: アドレスハッシュマップのキーを全て表示
adress_form --> mail_create_form: 
deactivate adress_form
mail_create_form -> adress_form: 宛先フォーム起動
adress_form --> user: 宛先画面 

user -> adress_form: OKボタン押下
activate adress_form
opt 選択されているアドレスがある時
    adress_form -> adress_form: 選択アドレス情報マップに設定
end
adress_form -> adress_form: 宛先画面を閉じる
adress_form --> mail_create_form: 
deactivate adress_form
mail_create_form -> adress_form: 選択アドレスマップ取得
adress_form --> mail_create_form: 選択アドレスマップを
opt 選択アドレスマップがnullではない時
    mail_create_form -> mail_create_form: 宛先テキストボックスにカンマ区切りでアドレスを表示
end
mail_create_form --> user: 
deactivate mail_create_form

@enduml