@startuml

skinparam classAttributeIconSize 0

namespace メニュー #FFFFFF {
  class メニューフォーム {
    - ユーザー情報 : ユーザー情報
    + コンストラクタ(ユーザー情報 : ユーザー情報)
    - 画面モード切り替え() : void
    - 勤怠起動ボタンクリックイベント() : void
    - 予定起動ボタンクリックイベント() : void
    - メール起動ボタンクリックイベント() : void
    - 会議使用状況起動ボタンクリックイベント() : void
    - ユーザー管理起動ボタンクリックイベント() : void
    - 勤怠の一括エクセル出力起動ボタンクリックイベント() : void
    - ログアウトボタンクリックイベント() : void
  }
}

@enduml