@startuml
skinparam classAttributeIconSize 0
class ログインフォーム {
  + コンストラクタ()
  - ボタンクリックイベント() : void
  - 未入力チェック() : bool
}

class ログインロジック {
   + ユーザー情報 : ユーザー情報
   + コンストラクタ()
   + ユーザーチェック(ユーザーID : string, パスワード : string) : bool
   - パスワードチェック(パスワード : string, ハッシュ値 : string)
   + 権限取得() : void
}

class データベースアクセス {
   + ユーザー情報取得(ユーザーID : string) : ユーザー情報
}

class ユーザー情報 {
   + ユーザーID : String
   + パスワード : String
   + String 権限名 : String
}
@enduml